baseURL = "https://geturhaineson.netlify.com/"			# Site's URL
title = "HDB"								# Site's Name
theme = "manis-hugo-theme"
copyright = "&copy; 2017 Yurizal Susanto"	# Copyright notice. Note: You can use HTML tag here
pluralizeListTitles = false
paginate = 10								# Minimum number of item before paginate navigation show up
canonifyURL = true
#disqusShortname = ""                        # Your disqus shortname

[taxonomies]
	tag = "tags"


[params]
	debugCSS = false                        # If false, use minified CSS (ui.min.css)
	#disqusSections = ["blog"]               # list of section support disqus comments
	# Site meta description
	description = "My name is Matthe Haines and this blog will follow everything I have learned in R."
	tagline = "Haines Data Blog"   # Site's Tagline (Subtitle or Keyword)
	#themeAttrib = true                      # If true give attribution to this theme
	licenseURL = "/about/license"           # URL to license file, can be outside of your domain

	# 404 Configuration
	head404 = "Sorry, I can find what you want."
	sub404 = "Back to <a href='/'>Home</a>."

	colorTheme = "#ff8181"                  # Color of your website
	latestCount = 3                         # Maximum number of item in Latest Posts or Works
	faviconImg = ""                         # Path to site's favicon image
	dateFmt = "Jan 02, 2006"                # Date format in item list

	# Code Highlighting (HighlightJS)
	highlightJs = true
	highlightJsLanguages = [ "go" ]
	highlightJsStyle = "ocean"

	# Social Links
	email = "mhaine86@lakers.mercyhurst.edu"
	github = "https://github.com/mhaine86/"


# Language Configuration
defaultContentLanguage = "en"
# Edit this if you want to translate your blog
#[languages.in]
#	lang = "in"
#	languageName = "Bahasa Indonesia"
#	weight = 1
